spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cats
    username: kitty
    password: purrr
    driver-class-name: org.postgresql.Driver
#
#  security:
#    oauth2:
#      client:
#        registration:
#          spotify:
#            provider: spotify-provider
#            client-secret: ${CLIENT_SECRET}
#            client-id: ${CLIENT_ID}
#            client-authentication-method: basic
#            authorization-grant-type: authorization_code
#            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
#        provider:
#          spotify-provider:
#            authorization-uri: https://accounts.spotify.com/authorize
#            token-uri: https://accounts.spotify.com/api/token
#            user-info-uri: https://api.spotify.com/v1/me
#            user-name-attribute: display_name